name: Deploy Application

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      # Build and deploy the React frontend to S3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build React frontend
        working-directory: ./auto-trader
        run: |
          npm install
          npm run build

      - name: Deploy frontend to S3
        run: |
          aws s3 sync ./auto-trader/dist s3://cpsc-362-auto-trader --delete

      # Deploy the Flask backend to EC2
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Flask backend
        run: |
          ssh -o StrictHostKeyChecking=no admin@ec2-3-138-198-12.us-east-2.compute.amazonaws.com "bash CPSC-362-auto-trader/deploy.sh"
